[package]
name = "cheval"
version = "0.1.0"
edition = "2018"
description = "An arch linux mirrorlist generator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
celes = "1.0.6"
chrono = { version = "0.4.19", features = ["serde"] }
rayon = "1.5.0"
reqwest = { version = "0.11.3", features = ["blocking"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
xdglib = { version = "0.1.0", git = "https://github.com/Shemnei/xdglib" }
